
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ReCaptchaProvider } from "./ReCaptchaProvider";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

      <ReCaptchaProvider reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}>{children}</ReCaptchaProvider>

        </body>
    </html>
  )
}
